import './globals.scss';
import React from 'react';
import TopBar from './components/TopBar';
import MidBar from './components/MidBar';
import BotBar from './components/BotBar';
import { Html } from 'next/document';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <TopBar />
      <MidBar />
      <BotBar />
      <body>{children}</body>
    </div>
  );
}
